### ISSUE TITLE
[Low] Recherche - Smiley

### ISSUE THREAD

**Issue by JulienLamy76** [Open-Street-Art/osa-front#38]
Mettre un vrai smiley lorsque n'avons pas de résultats lors de la recherche plutôt que ":("

**Comment by evanlaj** [comment]
Vous en pensez quoi ?

![image.png](https://images.zenhubusercontent.com/604f967dea7fd5e1b64126c3/d45752c4-2087-492f-bb9a-6a0367450adf)

**Comment by arnaudperalta** [comment]
Résultat actuel : https://i.imgur.com/cPkoP2a.png

Commit : https://github.com/Open-Street-Art/osa-front/commit/9dbf073bca39f300fee6cc202cb9c09ec206e99e
