### ISSUE TITLE
[High] Loader

### ISSUE THREAD

**Issue by JulienLamy76** [Open-Street-Art/osa-front#39]
Ajouter un loader sur le chargement des pages contenant des données

**Comment by arnaudperalta** [comment]
La page d'administration ainsi que les deux recherches présentent désormais un loader de cette forme :

https://i.imgur.com/WdH0LZY.gif

Le commit en question :
https://github.com/Open-Street-Art/osa-front/commit/1dd22ab20a3aafcef3c6015ce469ce4e7a14ce54

**Comment by arnaudperalta** [comment]
Deuxième ajout sur la page d'une oeuvre ainsi que sur les pins :

https://i.imgur.com/llJ9jGv.gif
