### ISSUE TITLE
[Low] Recherche - Padding

### ISSUE THREAD

**Issue by JulienLamy76** [Open-Street-Art/osa-front#40]
Réduire le padding bottom en dessous des œuvres dans la fenêtre de résultats de recherche

**Comment by Nemtecl** [comment]
![image](https://user-images.githubusercontent.com/24937220/115440022-8f75c000-a20f-11eb-857d-6966a1ba3b81.png)

**Comment by Goffayoh** [comment]
Voici le nouveau padding : https://i.imgur.com/s3hHfB1.png

Changement effectué sur le commit : [7b755e4](https://github.com/Open-Street-Art/osa-front/commit/7b755e45f1330d8be38aab6077990a9b2e30a09e)
