### ISSUE TITLE
[Normal] Modale - Cursor pointer sur la croix

### ISSUE THREAD

**Issue by JulienLamy76** [Open-Street-Art/osa-front#42]
Ajouter un cursor pointer sur la croix des modales

**Comment by Nemtecl** [comment]
Visible en desktop

![image](https://user-images.githubusercontent.com/24937220/115439890-5dfcf480-a20f-11eb-8ae0-7c8f776e540c.png)

**Comment by arnaudperalta** [comment]
Réglé sur ce commit dans une branche dédié : https://github.com/Open-Street-Art/osa-front/commit/fd2488d26b6565317fecbc25c7af6591f1718d00
