### ISSUE TITLE
[High] Formulaire - Touche entrée

### ISSUE THREAD

**Issue by JulienLamy76** [Open-Street-Art/osa-front#43]
Lorsque l'on appuie sur la touche Entrée, valider le formulaire (de connexion et d'inscription)

**Comment by Nemtecl** [comment]
Duplicate of #31

**Comment by evanlaj** [comment]
feature ajoutée lors du commit ci-dessous

[Commit](https://github.com/Open-Street-Art/osa-front/commit/365c31427aec4b8cb2f84d3a182e40fd5a7b9ddc)
