### ISSUE TITLE
[Normal] .vscode - extensions.json

### ISSUE THREAD

**Issue by JulienLamy76** [Open-Street-Art/osa-front#45]
Ajouter un fichier extensions.json dans le dossier .vscode permettant de proposer les extensions pour toutes les personnes sur le projet (VSCode proposera des extensions recommandées)

**Comment by arnaudperalta** [comment]
Effectué sur ce commit https://github.com/Open-Street-Art/osa-front/commit/f7e3afa2456630c8a95dd30c6dee35d9959369fd
