### ISSUE TITLE
[Normal] Traduction - Gérer le pluriel

### ISSUE THREAD

**Issue by JulienLamy76** [Open-Street-Art/osa-front#46]
Gérer le pluriel (voir Vue I18n Pluralization)

**Comment by Goffayoh** [comment]
Changement effectué sur le profil : https://i.imgur.com/1qRu2t2.png

commit correspondant : [1b767a8](https://github.com/Open-Street-Art/osa-front/commit/1b767a87c1330d04850f9f9677133ba538331c49)
