### ISSUE TITLE
[Low] Axios - Services

### ISSUE THREAD

**Issue by JulienLamy76** [Open-Street-Art/osa-front#49]
Créer des services pour utiliser axios plutôt que d'utiliser axios directement dans les composants.
(Par exemple un service UserService pour les appels sur user, etc.)

**Comment by arnaudperalta** [comment]
Les appels axios ont été déplacés dans des mixins appellé axios<..>Service.js

https://github.com/Open-Street-Art/osa-front/commit/f12ad65b71f222705e9019438cdca5ebf21cb76b
